framework:
    secret: '%env(APP_SECRET)%'

    # habilita el Serializer para la API
    serializer:
        enabled: true

    # validación con PHP Attributes, no con annotations
    validation:
        enabled: true
        enable_attributes: true
    session: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
